@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZjBjM2JhOTFmYjg5NmEyODhiYWEyYSIsImlhdCI6MTc2MDYyMTQ3NywiZXhwIjoxNzYwNjIyMzc3fQ.fDRX84qpRjItlTch1OJv-rGv4p9lUId2nNp5TnI4t54
@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZjBjM2JhOTFmYjg5NmEyODhiYWEyYSIsImlhdCI6MTc2MDYyMTQ3NywiZXhwIjoxNzYxMjI2Mjc3fQ.aFFnmC0Zc-ujF49F6vOHQmrVhGrd6HOq5C8Fa-reqYI
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "manuecam2b@hotmail.fr",
  "password": "NewSecurePass123!"
}

###

POST http://localhost:3000/auth/change-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "SecurePass123!",
  "newPassword": "NewSecurePass123!"
}


###
POST http://localhost:3000/auth/logout
Authorization: Bearer {{token}}

###
POST http://localhost:3000/auth/forgot-password
Content-Type: application/json

{
  "email": "manuecam2b@hotmail.fr"
}
###

POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "email": "manuecam2b@hotmail.fr"
}
###
POST http://localhost:3000/tasks/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Acheter des légumes",
  "description": "Acheter des légumes frais pour la semaine",
  "deadline": "2024-10-10T12:00:00Z",
  "status": "overdue",
  "priority": "high",
  "isDone": false,
  "period": "day",
  "categoryName": "shopping"
}

###

GET http://localhost:3000/stats/taskByDay
Authorization: Bearer {{token}}

###