@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZjBjM2JhOTFmYjg5NmEyODhiYWEyYSIsImlhdCI6MTc2MTI5Mjg0NSwiZXhwIjoxNzYxMjkzNzQ1fQ.9uo-ysAL3CPgYTYbEMrpErrEuzrs1YXmrXVDmw5dCXY
@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZjBjM2JhOTFmYjg5NmEyODhiYWEyYSIsImlhdCI6MTc2MTI5Mjg0NSwiZXhwIjoxNzYxODk3NjQ1fQ.MhziHDqCVOOxT89ksQB6JfeU3tRs_T_T_eav1Q9zvTc
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "manuecam2b@hotmail.fr",
  "password": "NewSecurePass123!"
}

###

POST http://localhost:3000/auth/change-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "SecurePass123!",
  "newPassword": "NewSecurePass123!"
}


###
POST http://localhost:3000/auth/logout
Authorization: Bearer {{token}}

###
POST http://localhost:3000/auth/forgot-password
Content-Type: application/json

{
  "email": "manuecam2b@hotmail.fr"
}
###

POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "email": "manuecam2b@hotmail.fr"
}
###
POST http://localhost:3000/tasks/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Acheter des légumes",
  "description": "Acheter des légumes frais pour la semaine",
  "deadline": "2024-10-10T12:00:00Z",
  "status": "overdue",
  "priority": "high",
  "isDone": false,
  "period": "day",
  "categoryName": "shopping"
}

###

GET http://localhost:3000/stats/taskByDay
Authorization: Bearer {{token}}

###
PUT http://localhost:3000/tasks/68fb3259de546de72484ab02
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "isDone": true
}

###

PUT http://localhost:3000/tasks/68fb3259de546de72484ab02
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "isDone": true
}

###

GET http://localhost:3000/tasks/68fb3259de546de72484ab02
Authorization: Bearer {{token}}