@token= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGU4OGVkYmE3YjdlZmI2ZTAyZDdmMiIsImlhdCI6MTc1OTQxNDUwOSwiZXhwIjoxNzU5NDE1NDA5fQ.pUHsRMrS9kCk1NeK0jaccpbP65nrLWWal1VMGNkdUVg"
@refreshToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGU4OGVkYmE3YjdlZmI2ZTAyZDdmMiIsImlhdCI6MTc1OTQxNDUwOSwiZXhwIjoxNzYwMDE5MzA5fQ.BTKYHprs-2kVLeea1lkVfXomf7rpbr_37fJQ81hZlc0; Max-Age=604800; Path=/; Expires=Thu, 09 Oct 2025 14:15:09 GMT; HttpOnly; Partitioned; SameSite=Strict
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstname": "firstname3",
    "lastname": "lastname3",
    "email": "taaaaaf@example.com",
    "password": "password123"
}
###
